### ISSUE TITLE
Timeout error in loop with promised

### ISSUE THREAD

**Issue by trung2208** [mkozjak/node-telnet-client#130]
I am using telnet-client to connect to my servers.
Connect single server is successfully, but in loop it throw error.
**This is my code:**

````javascript
var list=[ip1,ip2,ip3,..];
for (var _host of list) {
 var params = {
        host: _host,
        port: 23,
        shellPrompt: "/ # ", //connect to a busybox machine
        timeout: 1500,
        username: "user",
        password: "pass"
        // removeEcho: 4
      };
  console.log(item);
  connection
    .connect(params)
    .then(
      function(prompt) {
        console.log("connected"); // can't run to here
        getData(_host,cb); // do some action 
      },
      function(error) {
        console.log("promises reject:", error);
      }
    )
    .catch(function(error) {
      // handle the throw (timeout)
      console.log("timeout!");
    });
}
}
````
**And this is error log:**
promises reject: Error: timeout
    at Socket.socket.setTimeout (D:\Project\websk\node_modules\telnet-client\lib\index.js:85:23)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:449:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: timeout
    at Socket.socket.setTimeout (D:\Project\websk\node_modules\telnet-client\lib\index.js:85:23)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:449:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
promises reject: Error: timeout
    at Socket.socket.setTimeout (D:\Project\websk\node_modules\telnet-client\lib\index.js:85:23)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:449:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: timeout
    at Socket.socket.setTimeout (D:\Project\websk\node_modules\telnet-client\lib\index.js:85:23)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:449:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by mkozjak** [comment]
Maybe a connection limit on the server?

**Comment by trung2208** [comment]
I don't think so. 
I using only one  connection per unix server. 
I tested on my local machines. 
It raise exeption but can't catch them.

**Comment by mkozjak** [comment]
@trung2208: Why are you using this prompt? `shellPrompt: "/ # "`. Are you connecting to BusyBox?

**Comment by mkozjak** [comment]
It'd also really help if you formatted your code and output text...

**Comment by trung2208** [comment]
Yes. I'm connecting to BusyBox. 
The problem  is connect to once server, it work correctly. But in the loop, no one can connect to server, it just throw Exception at first connection.

**Comment by mkozjak** [comment]
Can you put the server that works in the loop and see if it works that way?

**Comment by mkozjak** [comment]
Please reopen if needed!
