### ISSUE TITLE
Error: Cannot connect

### ISSUE THREAD

**Issue by rojamet** [mkozjak/node-telnet-client#137]
Hello,

I'm trying to access NASA's JPL's HORIZON data, through telnet. I can access their Telnet server through the Windows 10's Powershell command "telnet horizons.jpl.nasa.gov 6775" without any problem.

But I cannot reach this network through this library.

Here's my code:
```
const Telnet = require('telnet-client');

async function run() {
  let connection = new Telnet();

  let params = {
    host: 'horizons.jpl.nasa.gov',
    port: 6775,
    shellPrompt: '/ # ',
    timeout: 1500
  };

  try {
    await connection.connect(params);
  } catch(error) {
    console.log('error');
    console.log(error);
    process.exit(1);
    // handle the throw (timeout)
  }

  let res = await connection.exec('uptime')
  console.log('async result:', res);
}

run();
```
Here's the Powershell output:
```
> node app.js

error
Error: Cannot connect
    at Socket.socket.setTimeout (C:\Users\rjame\Developpement\ad-astra_api\node_modules\telnet-client\lib\index.js:81:25)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket._onTimeout (net.js:440:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ad-astra_api@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ad-astra_api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rjame\AppData\Roaming\npm-cache\_logs\2019-06-17T21_53_51_384Z-debug.log
```

I have no idea what is triggering this error.

**Comment by mkozjak** [comment]
Wrong shell prompt.
It should be something like `Horizons> C_X`.

**Comment by mazyn** [comment]
Hi, I tried connecting with `shellPrompt: '/Horizons> C_X/'` but it didn't work. I still get the `Cannot Connect` error. @rojamet did you manage to solve your problem?
