### ISSUE TITLE
Error on simple connection

### ISSUE THREAD

**Issue by guicunha** [mkozjak/node-telnet-client#139]
**CODE**

var Telnet = require('telnet-client')
var connection = new Telnet()

var params = {
    host: '192.168.61.12',
    port: 23,
    timeout: 4500,
    // removeEcho: 4
}

connection.connect(params)
    .then(function(prompt) {
        connection.exec(cmd)
            .then(function(res) {
                console.log('promises result:', res)
            })
    }, function(error) {
        console.log('promises reject:', error)
    })
    .catch(function(error) {
        // handle the throw (timeout)
    })

**ERROR MESSAGE**

guilherme@cromg-gerti:/Projetos/expect-node$ node index.js 
promises reject: Error: Cannot connect
    at Socket.socket.setTimeout (/home/guilherme/Projetos/expect-node/node_modules/telnet-client/lib/index.js:81:25)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:422:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
guilherme@cromg-gerti:/Projetos/expect-node$ telnet 192.168.61.12
Trying 192.168.61.12...
Connected to 192.168.61.12.
Escape character is '^]'.
login:

**Comment by mkozjak** [comment]
Shell prompt missing, login prompt missing...

**Comment by guicunha** [comment]
var params = {
    host: '192.168.61.12',
    port: 23,
    loginPrompt: 'login: ',
    passwordPrompt: 'Password: ',
    username: 'xxx',
    password: 'xxx',
    shellPrompt: '/(?:/ )?#\s/',
    timeout: 4500,
// removeEcho: 

$node index.js 
promises reject: Error: Cannot connect
    at Socket.socket.setTimeout (/home/guilherme/Projetos/expect-node/node_modules/telnet-client/lib/index.js:81:25)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:422:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by mkozjak** [comment]
RIght now you can only try tcpdump to see what's wrong.
