### ISSUE TITLE
Async connect never resolves unless negotiationMandatory=false

### ISSUE THREAD

**Issue by shaivyamahajan** [mkozjak/node-telnet-client#140]
https://github.com/mkozjak/node-telnet-client/blob/d9a75b99b4c7c8abb284111bf3359b4384cfb4f3/lib/index.js#L68

Was trying to use the async example, seems like the initial promise is never resolved unless negotiationMandatory param is set to false, might be a bug.

**Comment by mkozjak** [comment]
Hey, can you provide me with full source code you were using?

**Comment by shaivyamahajan** [comment]
```
'use strict';
const Telnet = require('telnet-client');
const connection = new Telnet();

var params = {
    host: '192.168.1.5',
    shellPrompt: '',
    echoLines: 0,
    irs: '\r',
    ors: '\r',
    separator: false,
    execTimeout: 200,
};

async function run() {
    let connection = new Telnet();

    try {
        await connection.connect(params);
        let res = await connection.exec('PW?');
        console.log('async response:', res);
    } catch (error) {
        console.error(error);
    }
}

run();
```
Fails with exception:
```
Error: Cannot connect
    at Socket.<anonymous> (---/node_modules/telnet-client/lib/index.js:81:25)
    at Object.onceWrapper (events.js:291:20)
    at Socket.emit (events.js:203:13)
    at Socket._onTimeout (net.js:434:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
``` 
Adding `negotiationMandatory: false` to `params` prevents the exception and I get the async response fine.  Don't know the telnet protocol too well so not sure what that flag does, couldn't find out much about it either.

**Comment by mkozjak** [comment]
shellPrompt basically can’t be ‘'.

**Comment by mkozjak** [comment]
See #141
