### ISSUE TITLE
'Cannot connect' problem

### ISSUE THREAD

**Issue by dima1206** [mkozjak/node-telnet-client#159]
I'm trying to create a simple telnet connection, but it fails (probably because I am beginner in telnet). Most similar questions here and on StackOverflow just have wrong `shellPrompt`, but I checked it as described [here](https://stackoverflow.com/a/46929358), and it is seems to be right. Here is example of connecting via terminal:
```
Trying 172.17.0.2...
Connected to 172.17.0.2.
Escape character is '^]'.
Ubuntu 17.10
28069746bd1b login: root
Password: 
Last login: Thu Mar 12 12:35:41 UTC 2020 from 172.17.0.1 on pts/1
Welcome to Ubuntu 17.10 (GNU/Linux 5.3.0-40-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

root@28069746bd1b:~# date
Thu Mar 12 12:38:06 UTC 2020
root@28069746bd1b:~# 
```
Here is my code:
```
var Telnet = require('telnet-client')
var connection = new Telnet()
var params = {
		host: "172.17.0.2",
		port: 23,
		timeout: 3000,
                login: 'root',
                password: 'malware',
                loginPrompt: 'login: ',
                passwordPrompt: 'Password: ',
                shellPrompt: ':~[^$]*#\s*$',
                //negotiationMandatory: false,
}

connection.on('timeout', function() { console.log('timeout') })
connection.on('close', function() { console.log('connection closed') })

connection.connect(params)
  .then(function(prompt) {
    console.log('connected:', prompt)
    connection.exec('date')
      .then(function(res) {
        console.log('exec result:', res)
      })
      .catch(function(error) {
        console.log('exec error:', error)
        connection.end()
      })
  })
  .catch(function(error) {
    console.log('connect reject:', error)
  })
```
And here is what I'm getting from it:
```
connect reject: Error: Cannot connect
    at Socket.<anonymous> (/home/dima1206/d/test/node_modules/telnet-client/lib/index.js:85:25)
    at Object.onceWrapper (events.js:417:28)
    at Socket.emit (events.js:311:20)
    at Socket._onTimeout (net.js:478:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
connection closed
```
And when `negotiationMandatory: false` line is uncommented, I getting this:
```
connected: undefined
exec error: Error: response not received
    at Timeout._onTimeout (/home/dima1206/d/test/node_modules/telnet-client/lib/index.js:169:20)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
connection closed
```
My guess: TCP connection is established (since it is connected when `negotiationMandatory` is `false`) but it cannot parse login/password/shell prompts (does it receive them at all?) and just waiting for timeout. Am I doing something wrong?

In case it will be useful - I'm running telnet server with docker:
```
docker run -td --name=s1 --rm flemingcsi/telnet-server
docker inspect --format="s1: {{.NetworkSettings.IPAddress}}" s1  # show ip address, in this case 172.17.0.2
```

**Comment by mkozjak** [comment]
@dima1206 - thanks for using the lib! Unfortunately there’s no debugging mode available in the lib atm so the only thing you can do is dig deeper into the code to print all the values that are arriving through the socket. Check the data event internally and print the buffer out.

**Comment by dima1206** [comment]
Your advice helped - I found out that I didn't know how to write regex in js, thank you for help and sorry for trouble

**Comment by mkozjak** [comment]
Thank you so much, @dima1206!

**Comment by ImperadorSid** [comment]
@dima1206, how did you resolve this?

**Comment by dima1206** [comment]
@ImperadorSid, I put regexp between slashes instead of quotation marks, like this `shellPrompt: /:~[^$]*#\s*$/`
