### ISSUE TITLE
telnet unhandled rejection

### ISSUE THREAD

**Issue by Kaimunchi** [mkozjak/node-telnet-client#165]
i'm getting this error when i'm running code 

```
 Unhandled rejection Error: Cannot connect
    at Socket.<anonymous> (D:\New folder\node_modules\telnet-client\lib\index.js:85:25)
    at Object.onceWrapper (events.js:416:28)
    at Socket.emit (events.js:310:20)
    at Socket._onTimeout (net.js:479:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

this is my code 
```
 'use strict'
const Telnet =require('telnet-client')
const connection = new Telnet();
try{
    connection.connect({
        host: `1.2.3.4`,
        port: 6023,
        shellPrompt: `#`,
        loginPrompt: `Login`,
        timeout: 3000,
        username: `admin`,
        password: `admin`,
        failedLoginMatch: `Login incorrect`
    });
} catch (error){
    console.log(`Failed to login: ${error}`);
} 
```

**Comment by mkozjak** [comment]
Please format your code with backticks so everyone can see the code properly and possibly help!

**Comment by mkozjak** [comment]
@Kaimunchi, I edited it for you.

**Comment by mkozjak** [comment]
Insufficient info, and this isn't stackoverflow, anyway. Closing.

**Comment by Kaimunchi** [comment]
okay ,anyway thank you .
