### ISSUE TITLE
MaxListenersExceededWarning  Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by clarksheng** [mkozjak/node-telnet-client#207]
(node:7351) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 16 data listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:465:17)
    at Socket.addListener (node:events:487:10)
    at Socket.Readable.on (node:internal/streams/readable:876:35)
    at /Users/zhonghuasheng/Project/petroVendV2/node_modules/telnet-client/lib/index.js:285:33
    at new Promise (<anonymous>)
    at Telnet.<anonymous> (/Users/zhonghuasheng/Project/petroVendV2/node_modules/telnet-client/lib/index.js:264:44)
    at Generator.next (<anonymous>)
    at /Users/zhonghuasheng/Project/petroVendV2/node_modules/telnet-client/lib/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/zhonghuasheng/Project/petroVendV2/node_modules/telnet-client/lib/index.js:4:12)

**Comment by maciejwalendziuk** [comment]
hello,
I appear to get same memory leak warning. Seems to happen on looped connection.send(). Please consider reopening the issue. Node Version: v16.13.0 

```
(node:582556) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 16 data listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:465:17)
    at Socket.addListener (node:events:487:10)
    at Socket.Readable.on (node:internal/streams/readable:876:35)
    at /var/node/vocatus/node_modules/telnet-client/lib/index.js:285:33
    at new Promise (<anonymous>)
    at Telnet.<anonymous> (/var/node/vocatus/node_modules/telnet-client/lib/index.js:264:44)
    at Generator.next (<anonymous>)
    at /var/node/vocatus/node_modules/telnet-client/lib/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/var/node/vocatus/node_modules/telnet-client/lib/index.js:4:12)
```

**Comment by ErAz7** [comment]
any update here? this was crashing my production server, nothing improved yet on such an important bug!

**Comment by nbonamy** [comment]
https://github.com/mkozjak/node-telnet-client/pull/230

**Comment by ErAz7** [comment]
thanks but I switched to using nodejs `net` api and `socket` object directly, which is even more convinient than using `node-telnet-client`

**Comment by mkozjak** [comment]
#230 resolves this one.

**Comment by ErAz7** [comment]
Are you sure this was the reason behind memory leak when calling `connection.send` in a loop (with few seconds of delay between calls)? because when I was trying to fix the memory problem, I tried removing all listeners on the socket but although it seemed to reduce memory leak pace but didn't resolve it completely. Maybe that was a problem with my code though

**Comment by call8arshad** [comment]
Yesterday saw this same issue in my local development and thought to raise a PR with the fix.
I was late by 4 days. Kudos @nbonamy 🥇 

<img width="1174" alt="telnet-event-listener-Fix" src="https://user-images.githubusercontent.com/11881744/213406313-365f1838-1768-4225-9d50-ad6cd8b8443d.png">

**Comment by mkozjak** [comment]
@call8arshad thanks for the feedback! Did this solve your issue?

**Comment by call8arshad** [comment]
@mkozjak yes after the above change, it solves the issue.
I can confirm with the latest version this issue is not present.
