### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by xpro666** [mkozjak/node-telnet-client#68]
Hi, i install module and only require it to my project and get this error
e:\project\node_modules\telnet-client\lib\index.js:9
module.exports = class Telnet extends events.EventEmitter {
                 ^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (e:\projects\ca-server-easyrsa\components\openvpnmi.js:12:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

I add 'use strict'; to top of index.js to solve this trouble

**Comment by mkozjak** [comment]
Which node version are you using?

**Comment by maximdrozd** [comment]
node -v
v5.5.0

**Comment by maximdrozd** [comment]
if you add "use strict"; to index.js, you get the following:

/Users/max/node_modules/telnet-client/lib/index.js:352
    if (this.telnetSocket.writable) this.telnetSocket.write(Buffer.from(negResp, 'hex'))
                                                                   ^

TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at Telnet._negotiate (/Users/max/node_modules/telnet-client/lib/index.js:352:68)
    at Telnet._parseData (/Users/max/node_modules/telnet-client/lib/index.js:232:30)
    at Socket.<anonymous> (/Users/max/node_modules/telnet-client/lib/index.js:71:14)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:523:20)

**Comment by mkozjak** [comment]
Guys, please see the disclaimer here: https://github.com/mkozjak/node-telnet-client#responsible-disclosure

node v6.x is the minimum version required to run.
@maximdrozd: Are you not able to upgrade node for some reason?

**Comment by ektavasa** [comment]
Hi, 

I am also facing the same error mentioned above.
Node Version = 7.0.0
