### ISSUE TITLE
Syntax error =>

### ISSUE THREAD

**Issue by ektavasa** [mkozjak/node-telnet-client#69]
/node_modules/telnet-client/lib/index.js:17
    return new Promise(resolve => {
                               ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:434:25)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)

**Comment by mkozjak** [comment]
If you are getting this, you're not using the minimum required node.js version.

If you are, please post a full example of your code reproducing the issue.

**Comment by ektavasa** [comment]
I am using node7.0.0

**Comment by ektavasa** [comment]
Can you please tell me where can the issue be?

**Comment by mkozjak** [comment]
Please post a full example of your code reproducing the issue.
Also try running node -v && npm test against the master.
